### ISSUE TITLE
Not work automatically

### ISSUE THREAD

**Issue by mberizzo** [kduma/L5-eloquent-sluggable#2]
Hi! I have "products" table with "title" and "slug" fields,

In my model have this sentence "use \KDuma\Eloquent\Slugabble;". So, when i excecute save() method, the slug is not generated.

What am I doing wrong?

**Comment by kduma** [comment]
Show me your model. I have some idea what's wrong but I must saw your model. :)

**Comment by mberizzo** [comment]
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use \KDuma\Eloquent\Slugabble;

class Product extends Model {

	protected $table = 'products';

	public function category()
	{
		return $this->hasOne('App\Category');
	}

	public function images()
	{
		return $this->hasMany('App\Image');
	}

}

**Comment by kduma** [comment]
That's my fault that i wrote instruction unclear :) 
`use \KDuma\Eloquent\Slugabble;` should be added inside `Product` class (model) :)

```php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model {

	use \KDuma\Eloquent\Slugabble;

	protected $table = 'products';

	public function category()
	{
	    return $this->hasOne('App\Category');
	}

	public function images()
	{
	    return $this->hasMany('App\Image');
	}
}
```
Check now if it's working.

**Comment by mberizzo** [comment]
Now it's works!! thanks!

Yes, you need to add a clearer example in your documentation.

Why do i need to add this code into class?

**Comment by kduma** [comment]
`use` statement used in class imports [trait](http://php.net/manual/en/language.oop5.traits.php) to this class. When not used in class it only [imports](http://php.net/manual/en/language.namespaces.importing.php) that name to actual namespace.

**Comment by mberizzo** [comment]
thanks kduma!
