### ISSUE TITLE
save() and update() methods return null

### ISSUE THREAD

**Issue by mberizzo** [kduma/L5-eloquent-sluggable#3]
Hi, me again. Now i have "use \KDuma\Eloquent\Slugabble;" and it's work well.

The problem is: when i excecute this $status = $model->save(); the status var is "null". If i remove "use \KDuma\Eloquent\Slugabble;" $status is "true".

This problem is in update() method.

**Comment by kduma** [comment]
Missing return :) 

Do composer update to get updated version :)

**Comment by kduma** [comment]
To be honest I've didn't knew that `save()` is returning anything :)

**Comment by mberizzo** [comment]
haha, yes, return a status: true|false
